name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: p11/pokedex
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test